'use client'

import { useState, useRef, useEffect } from 'react'
import { submitAssignment } from '@/lib/utils/submitAssignment'

type Mode = 'quiz' | 'flashcards' | 'explain' | 'study-guide'
type TopStage = 'form' | 'loading' | 'quiz' | 'quiz-grading' | 'quiz-results' | 'flashcards' | 'flashcards-done' | 'explain' | 'study-guide'

interface QuizQuestion { question: string; options: string[] }
interface GradeFeedback { correct_index: number; explanation: string; your_answer: number }
interface FlashCard { front: string; back: string }
interface ExplainSection { heading: string; content: string }

interface QuizContent { title: string; sessionId: string; questions: QuizQuestion[] }
interface FlashcardContent { title: string; cards: FlashCard[] }
interface ExplainContent { title: string; sections: ExplainSection[]; summary: string }
interface StudyGuideContent {
  title: string; overview: string
  key_terms: { term: string; definition: string }[]
  main_concepts: { heading: string; content: string }[]
  remember: string[]
  practice_questions: { question: string; answer: string }[]
}

const MODES: { value: Mode; emoji: string; label: string; desc: string }[] = [
  { value: 'quiz',        emoji: '🧠', label: 'Quiz Me',      desc: '5 multiple-choice questions' },
  { value: 'flashcards',  emoji: '🃏', label: 'Flashcards',   desc: 'Key terms to flip through' },
  { value: 'explain',     emoji: '💡', label: 'Explain It',   desc: 'Simple breakdown of the ideas' },
  { value: 'study-guide', emoji: '📋', label: 'Study Guide',  desc: 'Terms, concepts, and practice Qs' },
]

const CHAR_WARN = 4000
const CHAR_MAX  = 5000

interface Props {
  isLoggedIn: boolean
  assignmentId?: string
  assignmentMaterial?: string
  assignmentMode?: Mode
  assignmentGrade?: number
}

export default function StudyHelper({ isLoggedIn, assignmentId, assignmentMaterial, assignmentMode, assignmentGrade }: Props) {
  const isAssignment = !!assignmentId

  // ── Form state (pre-seeded from assignment props when in assignment mode) ─
  const [material, setMaterial]   = useState(assignmentMaterial ?? '')
  const [mode, setMode]           = useState<Mode | null>(assignmentMode ?? null)
  const [grade, setGrade]         = useState<number | null>(assignmentGrade ?? null)
  const [error, setError]         = useState<string | null>(null)
  const [stage, setStage]         = useState<TopStage>('form')

  // ── Generated content ────────────────────────────────────────
  const [quizContent,       setQuizContent]       = useState<QuizContent | null>(null)
  const [flashcardContent,  setFlashcardContent]  = useState<FlashcardContent | null>(null)
  const [explainContent,    setExplainContent]    = useState<ExplainContent | null>(null)
  const [studyGuideContent, setStudyGuideContent] = useState<StudyGuideContent | null>(null)

  // ── Quiz sub-state ────────────────────────────────────────────
  const [currentQ,    setCurrentQ]    = useState(0)
  const [selected,    setSelected]    = useState<(number | null)[]>([])
  const [startedAt,   setStartedAt]   = useState<number>(0)
  const [quizScore,   setQuizScore]   = useState<{ score: number; total: number; feedback: GradeFeedback[] } | null>(null)

  // ── Flashcard sub-state ───────────────────────────────────────
  const [cardIndex, setCardIndex] = useState(0)
  const [flipped,   setFlipped]   = useState(false)
  const [known,     setKnown]     = useState<boolean[]>([])

  // ── Study guide open answers ──────────────────────────────────
  const [openAnswers, setOpenAnswers] = useState<Set<number>>(new Set())

  // ── Completion ────────────────────────────────────────────────
  const [xpEarned,   setXpEarned]   = useState<number | null | 'pending'>('pending')
  const completedRef    = useRef(false)
  const sessionIdRef    = useRef('')
  const autoGeneratedRef = useRef(false)

  // Auto-generate when all assignment props are present; surface error if assignment wasn't found
  useEffect(() => {
    if (!isAssignment) return
    if (!assignmentMaterial || !assignmentMode) {
      setError('Assignment not found or has been removed.')
      return
    }
    if (!autoGeneratedRef.current) {
      autoGeneratedRef.current = true
      handleGenerate()
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  async function handleGenerate() {
    if (!isAssignment) {
      if (!material.trim() || material.trim().length < 50) { setError('Please paste at least 50 characters of material.'); return }
      if (!mode) { setError('Choose a study mode first.'); return }
    }
    setError(null)
    setStage('loading')
    completedRef.current = false
    setXpEarned('pending')
    sessionIdRef.current = crypto.randomUUID()

    const res = await fetch('/api/study-helper/generate', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        material: material.trim(),
        mode,
        grade: grade ?? undefined,
        ...(assignmentId ? { assignmentId } : {}),
      }),
    })
    const data = await res.json()
    if (!res.ok) { setError(data.message); setStage('form'); return }

    if (mode === 'quiz') {
      setQuizContent(data)
      setSelected(Array(data.questions.length).fill(null))
      setCurrentQ(0)
      setStartedAt(Date.now())
      setStage('quiz')
    } else if (mode === 'flashcards') {
      setFlashcardContent(data)
      setKnown(Array(data.cards.length).fill(false))
      setCardIndex(0); setFlipped(false)
      setStage('flashcards')
    } else if (mode === 'explain') {
      setExplainContent(data)
      setStage('explain')
    } else {
      setStudyGuideContent(data)
      setOpenAnswers(new Set())
      setStage('study-guide')
    }
  }

  async function completeSession(opts: { score?: number; total?: number; quizSessionId?: string } = {}) {
    if (completedRef.current) return
    completedRef.current = true

    if (assignmentId) {
      const result = await submitAssignment(assignmentId, opts)
      setXpEarned(result?.xpEarned ?? null)
      return
    }

    const titlePreview =
      quizContent?.title ?? flashcardContent?.title ??
      explainContent?.title ?? studyGuideContent?.title ?? undefined

    try {
      const res = await fetch('/api/study-helper/complete', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ sessionId: sessionIdRef.current, mode, titlePreview, ...opts }),
      })
      if (res.ok) {
        const data = await res.json()
        setXpEarned(data.xpEarned ?? null)
      } else {
        setXpEarned(null)
      }
    } catch {
      setXpEarned(null)
    }
  }

  // Auto-complete after quiz results or flashcards finish (assignment mode only for the latter)
  useEffect(() => {
    if (stage === 'quiz-results' && quizScore) {
      completeSession({ score: quizScore.score, total: quizScore.total, quizSessionId: quizContent?.sessionId })
    }
    if (stage === 'flashcards-done' && isAssignment) {
      completeSession()
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [stage])

  async function handleQuizSubmit() {
    setStage('quiz-grading')
    const elapsedSeconds = Math.floor((Date.now() - startedAt) / 1000)

    const res = await fetch('/api/learning/quiz/grade', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ sessionId: quizContent!.sessionId, answers: selected, elapsedSeconds }),
    })
    const data = await res.json()
    if (!res.ok) { setError(data.message ?? 'Grading failed.'); setStage('quiz'); return }

    setQuizScore({ score: data.score, total: data.total, feedback: data.feedback })
    setStage('quiz-results')
  }

  function handleCardKnow(didKnow: boolean) {
    const next = [...known]; next[cardIndex] = didKnow; setKnown(next)
    if (cardIndex < flashcardContent!.cards.length - 1) {
      setCardIndex(i => i + 1); setFlipped(false)
    } else {
      setStage('flashcards-done')
    }
  }

  function reset() {
    setStage('form'); setMaterial(''); setMode(null); setGrade(null); setError(null)
    setQuizContent(null); setFlashcardContent(null); setExplainContent(null); setStudyGuideContent(null)
    setQuizScore(null); setSelected([]); setCurrentQ(0)
    setCardIndex(0); setFlipped(false); setKnown([])
    completedRef.current = false; setXpEarned('pending')
  }

  // ── XP / Quest banner ─────────────────────────────────────────
  function XpBanner({ quizAuto = false }: { quizAuto?: boolean }) {
    if (isAssignment) {
      if (xpEarned === 'pending') {
        if (!quizAuto) return null
        return (
          <div className="bg-indigo-50 border border-indigo-100 rounded-2xl px-5 py-4 text-center">
            <p className="text-xs text-indigo-400">Saving progress…</p>
          </div>
        )
      }
      return (
        <div className="bg-indigo-600 rounded-2xl px-5 py-4 flex items-center justify-between gap-4">
          <div>
            <p className="text-white font-semibold text-sm">Quest Complete! 🎉</p>
            <p className="text-indigo-200 text-xs">{xpEarned ? `+${xpEarned} XP earned` : 'Progress saved'}</p>
          </div>
          <a href="/classroom/student" className="bg-white text-indigo-600 text-xs font-bold px-4 py-2 rounded-xl whitespace-nowrap hover:bg-indigo-50 transition-colors shrink-0">
            Dashboard →
          </a>
        </div>
      )
    }

    if (!isLoggedIn) {
      return (
        <div className="bg-gray-50 border border-gray-200 rounded-2xl px-5 py-4 text-center">
          <p className="text-sm text-gray-500">
            <a href="/login" className="text-indigo-600 font-semibold hover:underline">Log in</a> to earn XP and save your progress.
          </p>
        </div>
      )
    }
    if (xpEarned === 'pending') {
      if (!quizAuto) return null
      return (
        <div className="bg-indigo-50 border border-indigo-100 rounded-2xl px-5 py-4 text-center">
          <p className="text-xs text-indigo-400">Saving progress…</p>
        </div>
      )
    }
    if (xpEarned === null || xpEarned === 0) {
      return (
        <div className="bg-gray-50 border border-gray-100 rounded-2xl px-5 py-4 text-center">
          <p className="text-sm text-gray-400">{xpEarned === 0 ? "You've hit your daily XP limit — come back tomorrow!" : 'Session saved.'}</p>
        </div>
      )
    }
    return (
      <div className="bg-indigo-600 rounded-2xl px-5 py-4 flex items-center justify-between gap-4">
        <div>
          <p className="text-white font-semibold text-sm">Session Complete! ✨</p>
          <p className="text-indigo-200 text-xs">+{xpEarned} XP earned</p>
        </div>
        <a href="/classroom/student" className="bg-white text-indigo-600 text-xs font-bold px-4 py-2 rounded-xl whitespace-nowrap hover:bg-indigo-50 transition-colors shrink-0">
          Dashboard →
        </a>
      </div>
    )
  }

  // ── FORM ──────────────────────────────────────────────────────
  if (stage === 'form') {
    if (isAssignment) {
      return (
        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm px-8 py-14 text-center space-y-4">
          {error ? (
            <>
              <div className="text-4xl">⚠️</div>
              <p className="text-sm font-medium text-red-500">{error}</p>
              <a href="/classroom/student" className="inline-block text-xs font-semibold text-indigo-600 hover:underline">← Back to Dashboard</a>
            </>
          ) : (
            <>
              <div className="w-10 h-10 border-2 border-indigo-200 border-t-indigo-500 rounded-full animate-spin mx-auto" />
              <p className="text-sm font-medium text-gray-600">Loading your assignment…</p>
            </>
          )}
        </div>
      )
    }
    const len = material.length
    return (
      <div className="space-y-5">
        {!isLoggedIn && (
          <div className="bg-amber-50 border border-amber-200 rounded-2xl px-4 py-3 text-sm text-amber-800">
            You can use this tool without an account, but XP and progress won&apos;t be saved unless you&apos;re{' '}
            <a href="/login" className="font-semibold underline">logged in</a>.
          </div>
        )}

        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm px-6 py-6 space-y-5">
          {/* Material input */}
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <label className="block text-sm font-semibold text-gray-700">Paste your notes or homework</label>
              <span className={`text-xs font-medium ${len > CHAR_WARN ? 'text-amber-500' : 'text-gray-400'}`}>
                {len}/{CHAR_MAX}
              </span>
            </div>
            {len > CHAR_WARN && len <= CHAR_MAX && (
              <p className="text-xs text-amber-600 bg-amber-50 rounded-lg px-3 py-2">
                Getting long — try to keep it under {CHAR_MAX} characters for best results.
              </p>
            )}
            <textarea
              rows={6}
              maxLength={CHAR_MAX}
              placeholder="Paste chapter notes, a paragraph from a textbook, spelling words, math definitions…"
              value={material}
              onChange={e => setMaterial(e.target.value)}
              className="w-full rounded-xl border border-gray-200 px-4 py-3 text-sm text-gray-900 placeholder:text-gray-300 focus:outline-none focus:ring-2 focus:ring-indigo-400 focus:border-transparent resize-none"
            />
          </div>

          {/* Mode selection */}
          <div className="space-y-2">
            <label className="block text-sm font-semibold text-gray-700">How do you want to study it?</label>
            <div className="grid grid-cols-2 gap-2">
              {MODES.map(m => (
                <button key={m.value} type="button" onClick={() => setMode(m.value)}
                  className={`text-left px-4 py-3 rounded-xl border-2 text-sm transition-all ${mode === m.value ? 'border-indigo-500 bg-indigo-50' : 'border-gray-200 bg-white hover:border-gray-300'}`}>
                  <span className="text-lg">{m.emoji}</span>
                  <p className={`font-semibold mt-1 ${mode === m.value ? 'text-indigo-700' : 'text-gray-700'}`}>{m.label}</p>
                  <p className={`text-xs mt-0.5 ${mode === m.value ? 'text-indigo-500' : 'text-gray-400'}`}>{m.desc}</p>
                </button>
              ))}
            </div>
          </div>

          {/* Grade (optional) */}
          <div className="space-y-2">
            <label className="block text-sm font-semibold text-gray-700">Grade <span className="text-gray-400 font-normal">(optional)</span></label>
            <div className="flex flex-wrap gap-2">
              {[1,2,3,4,5,6,7,8].map(g => (
                <button key={g} type="button" onClick={() => setGrade(grade === g ? null : g)}
                  className={`w-10 h-10 rounded-xl border-2 text-sm font-semibold transition-all ${grade === g ? 'border-indigo-500 bg-indigo-50 text-indigo-700' : 'border-gray-200 bg-white text-gray-500 hover:border-gray-300'}`}>
                  {g}
                </button>
              ))}
            </div>
          </div>

          {error && <p className="text-sm text-red-500 bg-red-50 rounded-xl px-4 py-3">{error}</p>}

          <button onClick={handleGenerate}
            disabled={material.trim().length < 50 || !mode}
            className="w-full py-3.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 disabled:bg-gray-200 disabled:text-gray-400 text-white font-semibold text-base transition-colors">
            Generate {mode ? MODES.find(m => m.value === mode)!.label : 'Activity'} →
          </button>
        </div>
      </div>
    )
  }

  // ── LOADING ───────────────────────────────────────────────────
  if (stage === 'loading') {
    return (
      <div className="bg-white rounded-2xl border border-gray-100 shadow-sm px-8 py-14 text-center space-y-4">
        <div className="w-10 h-10 border-2 border-indigo-200 border-t-indigo-500 rounded-full animate-spin mx-auto" />
        <p className="text-sm font-medium text-gray-600">Building your activity…</p>
        <p className="text-xs text-gray-400">Based on the material you pasted</p>
      </div>
    )
  }

  // ── QUIZ GRADING ──────────────────────────────────────────────
  if (stage === 'quiz-grading') {
    return (
      <div className="bg-white rounded-2xl border border-gray-100 shadow-sm px-8 py-14 text-center space-y-4">
        <div className="w-10 h-10 border-2 border-indigo-200 border-t-indigo-500 rounded-full animate-spin mx-auto" />
        <p className="text-sm font-medium text-gray-600">Grading your quiz…</p>
      </div>
    )
  }

  // ── QUIZ PLAYING ──────────────────────────────────────────────
  if (stage === 'quiz' && quizContent) {
    const q = quizContent.questions[currentQ]
    const allAnswered = selected.every(s => s !== null)
    return (
      <div className="space-y-4">
        <p className="text-xs text-gray-400 text-center">Based on the material you pasted</p>
        <div className="flex gap-2 justify-center">
          {quizContent.questions.map((_, i) => (
            <button key={i} onClick={() => setCurrentQ(i)}
              className={`w-2.5 h-2.5 rounded-full transition-all ${i === currentQ ? 'bg-indigo-600 scale-125' : selected[i] !== null ? 'bg-indigo-300' : 'bg-gray-200'}`} />
          ))}
        </div>
        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm px-6 py-5 space-y-2">
          <span className="text-xs font-semibold text-indigo-500 uppercase tracking-wide">Question {currentQ + 1} of {quizContent.questions.length}</span>
          <p className="text-base font-semibold text-gray-900 leading-snug">{q.question}</p>
        </div>
        <div className="space-y-2.5">
          {q.options.map((opt, i) => {
            const isSel = selected[currentQ] === i
            return (
              <button key={i} onClick={() => { const n = [...selected]; n[currentQ] = i; setSelected(n) }}
                className={`w-full text-left px-5 py-3.5 rounded-2xl border-2 text-sm transition-all font-medium ${isSel ? 'border-indigo-500 bg-indigo-50 text-indigo-800' : 'border-gray-200 bg-white text-gray-700 hover:border-gray-300 hover:bg-gray-50'}`}>
                <span className="inline-flex items-center gap-3">
                  <span className={`w-6 h-6 rounded-full border-2 flex items-center justify-center text-xs font-bold shrink-0 ${isSel ? 'border-indigo-500 bg-indigo-500 text-white' : 'border-gray-300 text-gray-400'}`}>{['A','B','C','D'][i]}</span>
                  {opt}
                </span>
              </button>
            )
          })}
        </div>
        {error && <p className="text-sm text-red-500 bg-red-50 rounded-xl px-4 py-3">{error}</p>}
        <div className="flex gap-3">
          {currentQ > 0 && (
            <button onClick={() => setCurrentQ(q => q - 1)} className="flex-1 py-3 rounded-xl border border-gray-200 text-sm font-semibold text-gray-600 hover:bg-gray-50 transition-colors">← Back</button>
          )}
          {currentQ < quizContent.questions.length - 1 ? (
            <button onClick={() => setCurrentQ(q => q + 1)} disabled={selected[currentQ] === null}
              className="flex-1 py-3 rounded-xl bg-indigo-600 hover:bg-indigo-500 disabled:bg-gray-200 disabled:text-gray-400 text-white font-semibold text-sm transition-colors">Next →</button>
          ) : (
            <button onClick={handleQuizSubmit} disabled={!allAnswered}
              className="flex-1 py-3 rounded-xl bg-indigo-600 hover:bg-indigo-500 disabled:bg-gray-200 disabled:text-gray-400 text-white font-semibold text-sm transition-colors">
              {allAnswered ? 'Submit Quiz →' : `${selected.filter(s => s !== null).length}/${quizContent.questions.length} answered`}
            </button>
          )}
        </div>
      </div>
    )
  }

  // ── QUIZ RESULTS ──────────────────────────────────────────────
  if (stage === 'quiz-results' && quizContent && quizScore) {
    const { score, total, feedback } = quizScore
    const pct = score / total
    return (
      <div className="space-y-4">
        <div className={`rounded-2xl px-6 py-6 text-center space-y-1 ${pct === 1 ? 'bg-yellow-50 border border-yellow-200' : pct >= 0.8 ? 'bg-green-50 border border-green-200' : pct >= 0.6 ? 'bg-blue-50 border border-blue-200' : 'bg-gray-50 border border-gray-200'}`}>
          <div className="text-4xl mb-2">{pct === 1 ? '🏆' : pct >= 0.8 ? '⭐' : pct >= 0.6 ? '👏' : '📚'}</div>
          <p className="text-2xl font-bold text-gray-900">{score} / {total}</p>
          <p className="text-sm font-medium text-gray-600">{pct === 1 ? 'Perfect score!' : pct >= 0.8 ? 'Great work!' : pct >= 0.6 ? 'Good effort!' : 'Keep studying!'}</p>
        </div>
        <XpBanner quizAuto />
        <div className="space-y-3">
          {quizContent.questions.map((q, i) => {
            const fb = feedback[i]
            const correct = fb.your_answer === fb.correct_index
            return (
              <div key={i} className={`bg-white rounded-2xl border-2 px-5 py-4 space-y-2 ${correct ? 'border-green-200' : 'border-red-200'}`}>
                <p className="text-sm font-semibold text-gray-800">{i + 1}. {q.question}</p>
                <div className="flex gap-2 flex-wrap">
                  <span className={`text-xs font-semibold px-2.5 py-1 rounded-full ${correct ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-600'}`}>{correct ? '✓ Correct' : `✗ You chose: ${q.options[fb.your_answer]}`}</span>
                  {!correct && <span className="text-xs font-semibold px-2.5 py-1 rounded-full bg-green-100 text-green-700">✓ {q.options[fb.correct_index]}</span>}
                </div>
                <p className="text-xs text-gray-500 italic">{fb.explanation}</p>
              </div>
            )
          })}
        </div>
        {!isAssignment && (
          <button onClick={reset} className="w-full py-3.5 rounded-xl border border-gray-200 text-gray-600 font-semibold text-sm hover:bg-gray-50 transition-colors">Study New Material</button>
        )}
      </div>
    )
  }

  // ── FLASHCARDS PLAYING ────────────────────────────────────────
  if (stage === 'flashcards' && flashcardContent) {
    const card = flashcardContent.cards[cardIndex]
    const knownCount = known.filter(Boolean).length
    return (
      <div className="space-y-4">
        <p className="text-xs text-gray-400 text-center">Based on the material you pasted</p>
        <div className="flex items-center justify-between text-xs text-gray-400">
          <span>{cardIndex + 1} of {flashcardContent.cards.length}</span>
          <span className="text-green-600 font-medium">{knownCount} known ✓</span>
        </div>
        <div className="w-full bg-gray-100 rounded-full h-1.5">
          <div className="bg-indigo-500 h-1.5 rounded-full transition-all" style={{ width: `${(cardIndex / flashcardContent.cards.length) * 100}%` }} />
        </div>
        <button onClick={() => setFlipped(f => !f)}
          className="w-full min-h-52 bg-white rounded-2xl border-2 border-gray-100 shadow-sm px-6 py-8 flex flex-col items-center justify-center gap-3 hover:border-indigo-200 hover:shadow-md transition-all">
          {!flipped ? (
            <>
              <span className="text-xs font-bold text-indigo-400 uppercase tracking-widest">Term</span>
              <p className="text-xl font-semibold text-gray-900 text-center leading-snug">{card.front}</p>
              <span className="text-xs text-gray-300 mt-2">Tap to reveal →</span>
            </>
          ) : (
            <>
              <span className="text-xs font-bold text-green-500 uppercase tracking-widest">Definition</span>
              <p className="text-base text-gray-700 text-center leading-relaxed">{card.back}</p>
            </>
          )}
        </button>
        {flipped ? (
          <div className="flex gap-3">
            <button onClick={() => handleCardKnow(false)}
              className="flex-1 py-3.5 rounded-xl border-2 border-red-200 bg-red-50 text-red-600 font-semibold text-sm hover:bg-red-100 transition-colors">Still learning 🔄</button>
            <button onClick={() => handleCardKnow(true)}
              className="flex-1 py-3.5 rounded-xl border-2 border-green-200 bg-green-50 text-green-700 font-semibold text-sm hover:bg-green-100 transition-colors">Got it ✓</button>
          </div>
        ) : (
          <div className="flex gap-3">
            {cardIndex > 0 && (
              <button onClick={() => { setCardIndex(i => i - 1); setFlipped(false) }}
                className="flex-1 py-3 rounded-xl border border-gray-200 text-sm font-semibold text-gray-600 hover:bg-gray-50 transition-colors">← Back</button>
            )}
            <button onClick={() => setFlipped(true)}
              className="flex-1 py-3 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-semibold text-sm transition-colors">Reveal Answer</button>
          </div>
        )}
      </div>
    )
  }

  // ── FLASHCARDS DONE ───────────────────────────────────────────
  if (stage === 'flashcards-done' && flashcardContent) {
    const knownCount = known.filter(Boolean).length
    const total = flashcardContent.cards.length
    return (
      <div className="space-y-4">
        <div className={`rounded-2xl px-6 py-6 text-center space-y-2 ${knownCount === total ? 'bg-yellow-50 border border-yellow-200' : 'bg-indigo-50 border border-indigo-200'}`}>
          <div className="text-4xl mb-1">{knownCount === total ? '🏆' : '📚'}</div>
          <p className="text-2xl font-bold text-gray-900">{knownCount} / {total}</p>
          <p className="text-sm text-gray-600">cards marked as known</p>
        </div>
        {knownCount < total && (
          <div className="bg-white rounded-xl border border-gray-100 px-4 py-3">
            <p className="text-sm font-medium text-gray-700 mb-2">Cards to review ({total - knownCount}):</p>
            {flashcardContent.cards.filter((_, i) => !known[i]).map((c, i) => (
              <div key={i} className="py-1.5 border-b border-gray-50 last:border-0">
                <p className="text-xs font-semibold text-gray-700">{c.front}</p>
                <p className="text-xs text-gray-400">{c.back}</p>
              </div>
            ))}
          </div>
        )}
        <XpBanner />
        <div className="flex flex-col gap-3">
          <button onClick={() => { setKnown(Array(flashcardContent.cards.length).fill(false)); setCardIndex(0); setFlipped(false); setStage('flashcards') }}
            className="w-full py-3.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-semibold text-sm transition-colors">Study Again</button>
          {!isAssignment && (
            <button onClick={reset}
              className="w-full py-3.5 rounded-xl border border-gray-200 text-gray-600 font-semibold text-sm hover:bg-gray-50 transition-colors">Study New Material</button>
          )}
        </div>
        {!isAssignment && xpEarned === 'pending' && (
          <button onClick={() => completeSession()}
            className="w-full py-3 rounded-xl bg-indigo-50 border border-indigo-200 text-indigo-700 font-semibold text-sm hover:bg-indigo-100 transition-colors">
            Mark as Complete {isLoggedIn ? '(earn XP)' : ''}
          </button>
        )}
      </div>
    )
  }

  // ── EXPLAIN ───────────────────────────────────────────────────
  if (stage === 'explain' && explainContent) {
    return (
      <div className="space-y-4">
        <p className="text-xs text-gray-400 text-center">Based on the material you pasted</p>
        <div className="bg-oxford rounded-2xl px-6 py-5 text-white">
          <p className="text-xs font-bold text-indigo-300 uppercase tracking-widest mb-1">Explanation</p>
          <h2 className="font-serif text-xl">{explainContent.title}</h2>
        </div>
        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm px-6 py-5 space-y-4">
          {explainContent.sections.map((s, i) => (
            <div key={i} className="space-y-1">
              <p className="text-sm font-semibold text-oxford">{s.heading}</p>
              <p className="text-sm text-gray-600 leading-relaxed">{s.content}</p>
            </div>
          ))}
        </div>
        {explainContent.summary && (
          <div className="bg-indigo-50 border border-indigo-100 rounded-2xl px-6 py-4">
            <p className="text-xs font-bold text-indigo-500 uppercase tracking-widest mb-2">Key Takeaway</p>
            <p className="text-sm text-indigo-800 leading-relaxed">{explainContent.summary}</p>
          </div>
        )}
        <XpBanner />
        {xpEarned === 'pending' && (
          <button onClick={() => completeSession()}
            className="w-full py-3.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-semibold text-sm transition-colors">
            {isAssignment ? 'Complete Quest →' : `Done Reading ${isLoggedIn ? '— Earn XP' : ''}`}
          </button>
        )}
        {!isAssignment && (
          <button onClick={reset}
            className="w-full py-3 rounded-xl border border-gray-200 text-gray-600 font-semibold text-sm hover:bg-gray-50 transition-colors">Study New Material</button>
        )}
      </div>
    )
  }

  // ── STUDY GUIDE ───────────────────────────────────────────────
  if (stage === 'study-guide' && studyGuideContent) {
    const sg = studyGuideContent
    return (
      <div className="space-y-4">
        <p className="text-xs text-gray-400 text-center">Based on the material you pasted</p>
        <div className="bg-oxford rounded-2xl px-6 py-5 text-white">
          <p className="text-xs font-bold text-indigo-300 uppercase tracking-widest mb-1">Study Guide</p>
          <h2 className="font-serif text-xl">{sg.title}</h2>
          <p className="text-sm mt-2" style={{ color: '#94a3b8' }}>{sg.overview}</p>
        </div>
        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm px-6 py-5 space-y-3">
          <p className="text-xs font-bold text-indigo-500 uppercase tracking-widest">Key Terms</p>
          <div className="grid gap-2">
            {sg.key_terms.map((t, i) => (
              <div key={i} className="flex gap-3 text-sm py-2 border-b border-gray-50 last:border-0">
                <span className="font-semibold text-oxford shrink-0 min-w-24">{t.term}</span>
                <span className="text-gray-600">{t.definition}</span>
              </div>
            ))}
          </div>
        </div>
        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm px-6 py-5 space-y-4">
          <p className="text-xs font-bold text-indigo-500 uppercase tracking-widest">Main Concepts</p>
          {sg.main_concepts.map((c, i) => (
            <div key={i} className="space-y-1">
              <p className="text-sm font-semibold text-oxford">{c.heading}</p>
              <p className="text-sm text-gray-600 leading-relaxed">{c.content}</p>
            </div>
          ))}
        </div>
        <div className="bg-indigo-50 border border-indigo-100 rounded-2xl px-6 py-5 space-y-3">
          <p className="text-xs font-bold text-indigo-500 uppercase tracking-widest">Remember 🧠</p>
          <ul className="space-y-2">
            {sg.remember.map((tip, i) => (
              <li key={i} className="flex gap-2 text-sm text-indigo-800"><span className="shrink-0">•</span>{tip}</li>
            ))}
          </ul>
        </div>
        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm px-6 py-5 space-y-3">
          <p className="text-xs font-bold text-indigo-500 uppercase tracking-widest">Practice Questions</p>
          {sg.practice_questions.map((pq, i) => (
            <div key={i} className="border border-gray-100 rounded-xl overflow-hidden">
              <button onClick={() => setOpenAnswers(prev => { const n = new Set(prev); n.has(i) ? n.delete(i) : n.add(i); return n })}
                className="w-full text-left px-4 py-3 flex items-start justify-between gap-3 hover:bg-gray-50 transition-colors">
                <p className="text-sm font-medium text-gray-800">{i + 1}. {pq.question}</p>
                <span className="text-gray-400 shrink-0 text-xs">{openAnswers.has(i) ? '▲' : '▼'}</span>
              </button>
              {openAnswers.has(i) && (
                <div className="px-4 pb-3 pt-1 bg-green-50 border-t border-gray-100">
                  <p className="text-sm text-green-800">{pq.answer}</p>
                </div>
              )}
            </div>
          ))}
        </div>
        <XpBanner />
        {xpEarned === 'pending' && (
          <button onClick={() => completeSession()}
            className="w-full py-3.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-semibold text-sm transition-colors">
            {isAssignment ? 'Complete Quest →' : `Done Studying ${isLoggedIn ? '— Earn XP' : ''}`}
          </button>
        )}
        {!isAssignment && (
          <button onClick={reset}
            className="w-full py-3 rounded-xl border border-gray-200 text-gray-600 font-semibold text-sm hover:bg-gray-50 transition-colors">Study New Material</button>
        )}
      </div>
    )
  }

  return null
}
