import Link from 'next/link'
import SiteHeader from '@/components/layout/SiteHeader'
import SiteFooter from '@/components/layout/SiteFooter'

export const metadata = { title: 'Terms of Service — Nest & Quill' }

export default function TermsPage() {
  return (
    <div className="h-dvh bg-parchment flex flex-col">
      <SiteHeader right={<Link href="/" className="text-sm text-charcoal-light hover:text-oxford">← Back</Link>} />

      <div className="flex-1 overflow-y-auto">
      <main className="max-w-3xl mx-auto px-6 py-14 space-y-10 w-full">
        <div>
          <h1 className="font-serif text-4xl text-oxford mb-3">Terms of Service</h1>
          <p className="text-sm text-charcoal-light">Last updated: April 2026</p>
          <p className="text-sm text-charcoal-light mt-1">Nest &amp; Quill is operated by Bright Tale Books.</p>
        </div>

        <Section title="Acceptance of Terms">
          <p>
            By accessing or using Nest &amp; Quill (&ldquo;the Service&rdquo;), you agree to be bound by these
            Terms of Service. If you do not agree, please do not use the Service.
            These terms apply to all visitors, users, and others who access the Service.
          </p>
        </Section>

        <Section title="Description of Service">
          <p>Nest &amp; Quill is an AI-powered platform that provides:</p>
          <ul>
            <li>Personalized story generation with illustrations</li>
            <li>Interactive learning tools (quizzes, flashcards, study guides, explanations, and practice tools)</li>
            <li>Classroom features for educators and students</li>
            <li>Study tools that transform user-provided material into learning activities</li>
          </ul>
          <p>Content is generated using artificial intelligence based on user inputs and preferences.</p>
        </Section>

        <Section title="Accounts">
          <p>You must provide accurate information when creating an account.</p>
          <p>You are responsible for maintaining the security of your account credentials.</p>
          <p>
            Users must be at least 18 years old to create an account independently. Students may access
            the Service through a classroom environment managed by a teacher or parent.
          </p>
          <p>Educators and parents are responsible for supervising student use of the Service.</p>
          <p>We reserve the right to suspend or terminate accounts that violate these terms.</p>
        </Section>

        <Section title="Educational Use">
          <p>
            Nest &amp; Quill is designed to support learning but does not replace formal instruction.
            Content generated by the Service may not always be accurate, complete, or appropriate for all
            situations. Users should review and verify generated content as needed.
          </p>
        </Section>

        <Section title="Payments and Refunds">
          <ul>
            <li>Paid plans are billed in advance on a monthly or annual basis.</li>
            <li>All payments are processed securely by Stripe.</li>
            <li>One-time story purchases are non-refundable once the story has been generated and delivered.</li>
            <li>Subscription plans may be cancelled at any time. Access continues through the end of the billing period.</li>
            <li>We reserve the right to change pricing with reasonable notice.</li>
          </ul>
        </Section>

        <Section title="Ownership of Generated Content">
          <p>
            When you purchase a story, you receive a personal, non-exclusive license to use, print,
            and share the generated storybook for personal, non-commercial purposes.
          </p>
          <p>
            You may not resell, redistribute, or commercially exploit generated content without written permission.
          </p>
          <p>
            Nest &amp; Quill retains ownership of the platform, AI systems, prompts, and underlying technology.
          </p>
        </Section>

        <Section title="Acceptable Use">
          <p>You agree not to use the Service to:</p>
          <ul>
            <li>Generate harmful, abusive, discriminatory, or illegal content</li>
            <li>Upload or input inappropriate or unsafe material</li>
            <li>Attempt to reverse engineer, scrape, or copy the platform</li>
            <li>Use bots or automation to abuse the system</li>
            <li>Impersonate another person or entity</li>
            <li>Violate any applicable laws</li>
          </ul>
          <p>We reserve the right to remove content or restrict access if these rules are violated.</p>
        </Section>

        <Section title="AI-Generated Content Disclaimer">
          <p>
            Content generated by Nest &amp; Quill, including stories, quizzes, explanations, and study tools,
            is created using artificial intelligence.
          </p>
          <p>
            While we strive for quality, AI-generated content may be imperfect, inaccurate, or unexpected.
            Nest &amp; Quill does not guarantee accuracy or suitability.
          </p>
        </Section>

        <Section title="Limitation of Liability">
          <p>
            To the maximum extent permitted by law, Nest &amp; Quill shall not be liable for indirect,
            incidental, or consequential damages arising from use of the Service.
          </p>
          <p>
            Total liability shall not exceed the amount paid by you in the 12 months preceding the claim.
          </p>
        </Section>

        <Section title="Changes to the Service">
          <p>
            We may modify or discontinue parts of the Service at any time. Continued use after changes
            indicates acceptance.
          </p>
        </Section>

        <Section title="Governing Law">
          <p>
            These terms are governed by the laws of the United States. Disputes will be resolved through
            binding arbitration where permitted.
          </p>
        </Section>

        <Section title="Contact">
          <p>
            For questions, contact:{' '}
            <a href="mailto:contact@nestandquill.com" className="text-brand-600 hover:text-brand-700">
              contact@nestandquill.com
            </a>.
          </p>
        </Section>
      </main>
      </div>
      <SiteFooter />
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-3">
      <h2 className="font-serif text-xl text-oxford">{title}</h2>
      <div className="text-sm text-charcoal leading-relaxed space-y-3 [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:space-y-1.5 [&_a]:text-brand-600 [&_a]:hover:text-brand-700">
        {children}
      </div>
    </section>
  )
}
