import Link from 'next/link'
import SiteHeader from '@/components/layout/SiteHeader'
import SiteFooter from '@/components/layout/SiteFooter'

export const metadata = { title: 'Terms of Service — Nest & Quill' }

export default function TermsPage() {
  return (
    <div className="h-dvh bg-parchment flex flex-col">
      <SiteHeader right={<Link href="/" className="text-sm text-charcoal-light hover:text-oxford">← Back</Link>} />

      <div className="flex-1 overflow-y-auto">
      <main className="max-w-3xl mx-auto px-6 py-14 space-y-10 w-full">
        <div>
          <h1 className="font-serif text-4xl text-oxford mb-3">Terms of Service</h1>
          <p className="text-sm text-charcoal-light">Last updated: April 2025</p>
          <p className="text-sm text-charcoal-light mt-1">Nest &amp; Quill is operated by Bright Tale Books.</p>
        </div>

        <Section title="Acceptance of terms">
          <p>
            By accessing or using Nest &amp; Quill (&ldquo;the Service&rdquo;), you agree to be bound by these
            Terms of Service. If you do not agree, please do not use the Service.
            These terms apply to all visitors, users, and others who access the Service.
          </p>
        </Section>

        <Section title="Description of service">
          <p>
            Nest &amp; Quill is an AI-powered platform that generates personalized illustrated storybooks.
            You provide details about a child and story preferences, and we produce a unique story with
            AI-generated text and illustrations, available to read online and download as a PDF.
          </p>
        </Section>

        <Section title="Accounts">
          <ul>
            <li>You must provide accurate information when creating an account.</li>
            <li>You are responsible for maintaining the security of your account credentials.</li>
            <li>You must be at least 18 years old to create an account and purchase stories.</li>
            <li>We reserve the right to suspend or terminate accounts that violate these terms.</li>
          </ul>
        </Section>

        <Section title="Payments and refunds">
          <ul>
            <li>Paid plans are billed in advance on a monthly or annual basis.</li>
            <li>All payments are processed securely by Stripe.</li>
            <li>One-time story purchases are non-refundable once the story has been generated and delivered.</li>
            <li>Subscription plans may be cancelled at any time. You will retain access until the end of your current billing period.</li>
            <li>We reserve the right to change pricing with 30 days notice to existing subscribers.</li>
          </ul>
        </Section>

        <Section title="Ownership of generated content">
          <p>
            When you purchase a story, you receive a personal, non-exclusive license to use, print,
            and share the generated storybook for personal, non-commercial purposes. You may print
            physical copies for personal use or as gifts.
          </p>
          <p>
            You may not resell, redistribute, or commercially exploit the generated content without
            our written permission. Nest &amp; Quill retains ownership of the underlying AI models,
            prompts, and platform technology.
          </p>
        </Section>

        <Section title="Acceptable use">
          <p>You agree not to use the Service to:</p>
          <ul>
            <li>Generate content that is harmful, abusive, discriminatory, or illegal.</li>
            <li>Attempt to reverse engineer, scrape, or copy the platform or its AI systems.</li>
            <li>Use automated scripts or bots to create stories in bulk.</li>
            <li>Impersonate another person or entity.</li>
            <li>Violate any applicable laws or regulations.</li>
          </ul>
          <p>We reserve the right to refuse or remove any content that violates these guidelines.</p>
        </Section>

        <Section title="AI-generated content disclaimer">
          <p>
            Stories and illustrations are generated by artificial intelligence. While we strive for
            quality and appropriateness, AI-generated content may occasionally be imperfect, unexpected,
            or require review. We are not liable for the accuracy or suitability of any generated content.
            If you receive a story that is inappropriate or fails to generate correctly, please contact us
            and we will work to resolve the issue.
          </p>
        </Section>

        <Section title="Limitation of liability">
          <p>
            To the maximum extent permitted by law, Nest &amp; Quill shall not be liable for any indirect,
            incidental, special, or consequential damages arising from your use of the Service.
            Our total liability for any claim arising under these terms shall not exceed the amount
            you paid us in the 12 months preceding the claim.
          </p>
        </Section>

        <Section title="Changes to the service">
          <p>
            We reserve the right to modify or discontinue any part of the Service at any time.
            We will provide reasonable notice of significant changes. Continued use of the Service
            after changes constitutes your acceptance of the updated terms.
          </p>
        </Section>

        <Section title="Governing law">
          <p>
            These terms are governed by the laws of the United States. Any disputes shall be
            resolved through binding arbitration, except where prohibited by law.
          </p>
        </Section>

        <Section title="Contact">
          <p>
            Questions about these terms? Email us at{' '}
            <a href="mailto:contact@nestandquill.com" className="text-brand-600 hover:text-brand-700">
              contact@nestandquill.com
            </a>.
          </p>
        </Section>
      </main>
      </div>
      <SiteFooter />
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-3">
      <h2 className="font-serif text-xl text-oxford">{title}</h2>
      <div className="text-sm text-charcoal leading-relaxed space-y-3 [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:space-y-1.5 [&_a]:text-brand-600 [&_a]:hover:text-brand-700">
        {children}
      </div>
    </section>
  )
}
