/**
 * Legal copy (Terms of Service, Privacy Policy) in both languages.
 *
 * The English text is the authoritative policy, reproduced verbatim from the
 * page it replaces. The Spanish text is a faithful translation of the same
 * rules — never a different policy. Sections flagged `beta` render only while
 * Beta Mode is on, exactly as before.
 */
import type { Lang } from './index.ts'

export type LegalBlock =
  | { p: string }
  | { ul: string[] }
  | { strong: string }
  | { contact: string }

export interface LegalSection {
  title: string
  beta?: boolean
  blocks: LegalBlock[]
  /** Extra bullet shown inside this section only while Beta Mode is on. */
  betaBullet?: string
}

export interface LegalDoc {
  title: string
  updated: string
  operator: string
  sections: LegalSection[]
}

const CONTACT = 'contact@nestandquill.com'

const termsEn: LegalDoc = {
  title: 'Terms of Service',
  updated: 'Last updated: May 2026',
  operator: 'Nest & Quill is operated by Bright Tale Books.',
  sections: [
    { title: 'Acceptance of Terms', blocks: [
      { p: 'By accessing or using Nest & Quill (“the Service”), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service. These terms apply to all visitors, users, and others who access the Service.' },
    ] },
    { title: 'Description of Service', blocks: [
      { p: 'Nest & Quill is an AI-powered platform that provides:' },
      { ul: ['Personalized story generation with illustrations', 'Interactive learning tools (quizzes, flashcards, matching, fill-in-the-blank, puzzles, trivia, study guides, explanations, and practice tools)', 'Classroom features for educators and students', 'Study tools that transform user-provided material into learning activities'] },
      { p: 'Content is generated using artificial intelligence based on user inputs and preferences.' },
    ] },
    { title: 'Beta Period', beta: true, blocks: [
      { p: 'The Service is currently in beta. During this period:' },
      { ul: ['Paid plans may be available at no charge while we evaluate the experience. We will notify users in advance before activating billing.', 'Some capabilities (such as automatic illustration generation) may be paused, limited, or simulated to control infrastructure costs. Stories may deliver as text-only during these windows.', 'Features may be added, changed, or removed without prior notice.'] },
      { p: 'We do our best to keep beta limitations transparent in the product UI and in transactional emails.' },
    ] },
    { title: 'Accounts', blocks: [
      { p: 'You must provide accurate information when creating an account.' },
      { p: 'You are responsible for maintaining the security of your account credentials.' },
      { p: 'Users must be at least 18 years old to create an account independently. Students may access the Service through a classroom environment managed by a teacher or parent.' },
      { p: 'Educators and parents are responsible for supervising student use of the Service.' },
      { p: 'We reserve the right to suspend or terminate accounts that violate these terms.' },
    ] },
    { title: 'Educational Use', blocks: [
      { p: 'Nest & Quill is designed to support learning but does not replace formal instruction. Content generated by the Service may not always be accurate, complete, or appropriate for all situations. Users should review and verify generated content as needed.' },
    ] },
    { title: 'Classroom Use', blocks: [
      { p: 'Educators may create classrooms, share a join code with students, and assign learning activities. By creating a classroom, the educator confirms they are authorized by their school, district, or family to enroll the participating students.' },
      { p: 'Educators control:' },
      { ul: ['Which students join the classroom (via join code).', 'Which activities are assigned and the content backing those activities.', 'Removal of student submissions and removal of the classroom itself.'] },
      { p: "Students can review and complete only the activities the educator has assigned to them. Students do not have access to other students' submissions unless the educator enables that within a specific feature." },
      { p: 'Nest & Quill may suspend or remove classrooms that violate these Terms or the Acceptable Use policy.' },
    ] },
    { title: 'Payments and Refunds', betaBullet: 'During beta, paid plans may be free while we evaluate the experience.', blocks: [
      { ul: ['Paid plans are billed in advance on a monthly, annual, or one-time basis.', 'All payments are processed securely by Stripe. We do not store full credit card numbers on our servers.', 'One-time story purchases are non-refundable once the story has been generated and delivered.', 'Subscription plans may be cancelled at any time. Access continues through the end of the billing period.', 'We reserve the right to change pricing with reasonable notice.'] },
    ] },
    { title: 'Ownership of Generated Content', blocks: [
      { p: 'When you purchase a story, you receive a personal, non-exclusive license to use, print, and share the generated storybook for personal, non-commercial purposes.' },
      { p: 'You may not resell, redistribute, or commercially exploit generated content without written permission.' },
      { p: 'Nest & Quill retains ownership of the platform, AI systems, prompts, and underlying technology.' },
    ] },
    { title: 'Archive and Deletion', blocks: [
      { p: 'You may archive stories from your account; archived stories remain in our system in a hidden state and can be restored.' },
      { p: 'To request permanent deletion of your account or of specific stories, contact us at the email below. Permanent deletion removes content from active systems within 30 days, subject to backup retention windows that may take slightly longer to roll over.' },
    ] },
    { title: 'Acceptable Use', blocks: [
      { p: 'You agree not to use the Service to:' },
      { ul: ['Generate harmful, abusive, discriminatory, or illegal content', 'Upload or input inappropriate or unsafe material', 'Attempt to reverse engineer, scrape, or copy the platform', 'Use bots or automation to abuse the system', 'Impersonate another person or entity', 'Violate any applicable laws'] },
      { p: 'We reserve the right to remove content or restrict access if these rules are violated.' },
    ] },
    { title: 'Adult Content', blocks: [
      { p: 'Nest & Quill offers story creation for adult readers (18+). By selecting the adult option, you confirm that you are at least 18 years old.' },
      { p: "Adult stories may contain more complex themes, mature narratives, and content that differs in tone from our children's stories. Adult content is generated using a separate AI configuration designed for mature audiences." },
      { p: 'Adult stories are not suitable for children. Users are responsible for ensuring that adult content is not shared with or accessible to minors.' },
      { p: 'We reserve the right to moderate, restrict, or remove adult content that violates our acceptable use policy or applicable laws.' },
    ] },
    { title: 'AI-Generated Content Disclaimer', blocks: [
      { p: 'Content generated by Nest & Quill, including stories, quizzes, explanations, and study tools, is created using artificial intelligence.' },
      { p: 'While we strive for quality, AI-generated content may be imperfect, inaccurate, or unexpected. Nest & Quill does not guarantee accuracy or suitability.' },
    ] },
    { title: 'Limitation of Liability', blocks: [
      { p: 'To the maximum extent permitted by law, Nest & Quill shall not be liable for indirect, incidental, or consequential damages arising from use of the Service.' },
      { p: 'Total liability shall not exceed the amount paid by you in the 12 months preceding the claim.' },
    ] },
    { title: 'Changes to the Service', blocks: [
      { p: 'We may modify or discontinue parts of the Service at any time. Continued use after changes indicates acceptance.' },
    ] },
    { title: 'Governing Law', blocks: [
      { p: 'These terms are governed by the laws of the United States. Disputes will be resolved through binding arbitration where permitted.' },
    ] },
    { title: 'Contact', blocks: [{ contact: 'For questions, contact:' }] },
  ],
}

const termsEs: LegalDoc = {
  title: 'Términos de servicio',
  updated: 'Última actualización: mayo de 2026',
  operator: 'Nest & Quill es operado por Bright Tale Books.',
  sections: [
    { title: 'Aceptación de los términos', blocks: [
      { p: 'Al acceder o usar Nest & Quill (“el Servicio”), aceptas quedar sujeto a estos Términos de servicio. Si no estás de acuerdo, por favor no uses el Servicio. Estos términos se aplican a todos los visitantes, usuarios y demás personas que accedan al Servicio.' },
    ] },
    { title: 'Descripción del servicio', blocks: [
      { p: 'Nest & Quill es una plataforma impulsada por inteligencia artificial que ofrece:' },
      { ul: ['Generación de cuentos personalizados con ilustraciones', 'Herramientas de aprendizaje interactivas (cuestionarios, tarjetas de memoria, emparejar, completar espacios, rompecabezas, trivia, guías de estudio, explicaciones y herramientas de práctica)', 'Funciones de salón de clases para educadores y estudiantes', 'Herramientas de estudio que transforman el material proporcionado por el usuario en actividades de aprendizaje'] },
      { p: 'El contenido se genera mediante inteligencia artificial a partir de las entradas y preferencias del usuario.' },
    ] },
    { title: 'Periodo beta', beta: true, blocks: [
      { p: 'El Servicio se encuentra actualmente en beta. Durante este periodo:' },
      { ul: ['Los planes de pago pueden estar disponibles sin costo mientras evaluamos la experiencia. Avisaremos a los usuarios con anticipación antes de activar la facturación.', 'Algunas capacidades (como la generación automática de ilustraciones) pueden pausarse, limitarse o simularse para controlar los costos de infraestructura. Durante esos periodos, los cuentos pueden entregarse solo con texto.', 'Las funciones pueden agregarse, cambiarse o eliminarse sin previo aviso.'] },
      { p: 'Hacemos lo posible por mantener las limitaciones de la beta transparentes en la interfaz del producto y en los correos transaccionales.' },
    ] },
    { title: 'Cuentas', blocks: [
      { p: 'Debes proporcionar información precisa al crear una cuenta.' },
      { p: 'Eres responsable de mantener la seguridad de las credenciales de tu cuenta.' },
      { p: 'Los usuarios deben tener al menos 18 años para crear una cuenta por sí mismos. Los estudiantes pueden acceder al Servicio a través de un entorno de salón de clases administrado por un maestro o un padre.' },
      { p: 'Los educadores y los padres son responsables de supervisar el uso del Servicio por parte de los estudiantes.' },
      { p: 'Nos reservamos el derecho de suspender o cancelar las cuentas que infrinjan estos términos.' },
    ] },
    { title: 'Uso educativo', blocks: [
      { p: 'Nest & Quill está diseñado para apoyar el aprendizaje, pero no sustituye la enseñanza formal. El contenido generado por el Servicio puede no ser siempre preciso, completo o apropiado para todas las situaciones. Los usuarios deben revisar y verificar el contenido generado según sea necesario.' },
    ] },
    { title: 'Uso en el salón de clases', blocks: [
      { p: 'Los educadores pueden crear salones de clases, compartir un código de acceso con los estudiantes y asignar actividades de aprendizaje. Al crear un salón, el educador confirma que está autorizado por su escuela, distrito o familia para inscribir a los estudiantes participantes.' },
      { p: 'Los educadores controlan:' },
      { ul: ['Qué estudiantes se unen al salón (mediante el código de acceso).', 'Qué actividades se asignan y el contenido que las respalda.', 'La eliminación de las entregas de los estudiantes y la eliminación del propio salón.'] },
      { p: 'Los estudiantes solo pueden revisar y completar las actividades que el educador les haya asignado. Los estudiantes no tienen acceso a las entregas de otros estudiantes a menos que el educador lo habilite dentro de una función específica.' },
      { p: 'Nest & Quill puede suspender o eliminar los salones que infrinjan estos Términos o la política de uso aceptable.' },
    ] },
    { title: 'Pagos y reembolsos', betaBullet: 'Durante la beta, los planes de pago pueden ser gratuitos mientras evaluamos la experiencia.', blocks: [
      { ul: ['Los planes de pago se facturan por adelantado de forma mensual, anual o como pago único.', 'Todos los pagos se procesan de forma segura a través de Stripe. No almacenamos números completos de tarjetas de crédito en nuestros servidores.', 'Las compras de cuentos individuales no son reembolsables una vez que el cuento ha sido generado y entregado.', 'Los planes de suscripción pueden cancelarse en cualquier momento. El acceso continúa hasta el final del periodo de facturación.', 'Nos reservamos el derecho de cambiar los precios con un aviso razonable.'] },
    ] },
    { title: 'Propiedad del contenido generado', blocks: [
      { p: 'Cuando compras un cuento, recibes una licencia personal y no exclusiva para usar, imprimir y compartir el libro generado con fines personales y no comerciales.' },
      { p: 'No puedes revender, redistribuir ni explotar comercialmente el contenido generado sin permiso por escrito.' },
      { p: 'Nest & Quill conserva la propiedad de la plataforma, los sistemas de IA, las instrucciones (prompts) y la tecnología subyacente.' },
    ] },
    { title: 'Archivo y eliminación', blocks: [
      { p: 'Puedes archivar cuentos desde tu cuenta; los cuentos archivados permanecen en nuestro sistema en estado oculto y pueden restaurarse.' },
      { p: 'Para solicitar la eliminación permanente de tu cuenta o de cuentos específicos, contáctanos en el correo indicado abajo. La eliminación permanente retira el contenido de los sistemas activos en un plazo de 30 días, sujeto a los periodos de retención de copias de seguridad, que pueden tardar un poco más en renovarse.' },
    ] },
    { title: 'Uso aceptable', blocks: [
      { p: 'Te comprometes a no usar el Servicio para:' },
      { ul: ['Generar contenido dañino, abusivo, discriminatorio o ilegal', 'Subir o ingresar material inapropiado o inseguro', 'Intentar realizar ingeniería inversa, extraer datos o copiar la plataforma', 'Usar bots o automatización para abusar del sistema', 'Suplantar a otra persona o entidad', 'Infringir cualquier ley aplicable'] },
      { p: 'Nos reservamos el derecho de eliminar contenido o restringir el acceso si se infringen estas reglas.' },
    ] },
    { title: 'Contenido para adultos', blocks: [
      { p: 'Nest & Quill ofrece la creación de historias para lectores adultos (18+). Al seleccionar la opción para adultos, confirmas que tienes al menos 18 años.' },
      { p: 'Las historias para adultos pueden contener temas más complejos, narrativas maduras y contenido con un tono distinto al de nuestros cuentos infantiles. El contenido para adultos se genera con una configuración de IA independiente diseñada para audiencias maduras.' },
      { p: 'Las historias para adultos no son aptas para niños. Los usuarios son responsables de asegurarse de que el contenido para adultos no se comparta con menores ni sea accesible para ellos.' },
      { p: 'Nos reservamos el derecho de moderar, restringir o eliminar el contenido para adultos que infrinja nuestra política de uso aceptable o las leyes aplicables.' },
    ] },
    { title: 'Aviso sobre el contenido generado por IA', blocks: [
      { p: 'El contenido generado por Nest & Quill, incluidos los cuentos, los cuestionarios, las explicaciones y las herramientas de estudio, se crea mediante inteligencia artificial.' },
      { p: 'Aunque buscamos la calidad, el contenido generado por IA puede ser imperfecto, inexacto o inesperado. Nest & Quill no garantiza su precisión ni su idoneidad.' },
    ] },
    { title: 'Limitación de responsabilidad', blocks: [
      { p: 'En la máxima medida permitida por la ley, Nest & Quill no será responsable de daños indirectos, incidentales o consecuentes derivados del uso del Servicio.' },
      { p: 'La responsabilidad total no excederá el monto que hayas pagado en los 12 meses anteriores a la reclamación.' },
    ] },
    { title: 'Cambios en el servicio', blocks: [
      { p: 'Podemos modificar o descontinuar partes del Servicio en cualquier momento. El uso continuado después de los cambios indica su aceptación.' },
    ] },
    { title: 'Ley aplicable', blocks: [
      { p: 'Estos términos se rigen por las leyes de los Estados Unidos. Las disputas se resolverán mediante arbitraje vinculante cuando esté permitido.' },
    ] },
    { title: 'Contacto', blocks: [{ contact: 'Si tienes preguntas, escríbenos a:' }] },
  ],
}

const privacyEn: LegalDoc = {
  title: 'Privacy Policy',
  updated: 'Last updated: May 2026',
  operator: 'Nest & Quill is operated by Bright Tale Books.',
  sections: [
    { title: 'Overview', blocks: [
      { p: 'This Privacy Policy explains what information we collect, how we use it, and how we protect it.' },
      { p: 'By using the Service, you agree to this policy.' },
    ] },
    { title: 'Beta Notice', beta: true, blocks: [
      { p: 'Nest & Quill is currently in beta. Some paid features may be free during this period and certain capabilities (such as illustration generation) may be paused or limited. We will give reasonable notice before enabling billing or removing beta accommodations.' },
    ] },
    { title: 'Information We Collect', blocks: [
      { strong: 'Account Information' },
      { ul: ['Name', 'Email address', 'Account role (parent, student, educator)', 'Guest token (a per-browser cookie) when you submit a story without signing in, so we can show you the story in progress and, if you later create an account with the same email, link the story to your account.'] },
      { strong: 'User Content' },
      { ul: ['Story inputs and preferences (including drafts and submitted stories)', 'Study Helper material (text or images you provide for learning)', 'Quiz answers, flashcard responses, and other learning-activity submissions', 'In-app notifications addressed to your account (titles, links, read state)'] },
      { strong: 'Classroom Data' },
      { ul: ['Class memberships', 'Assignments and submissions', 'Progress data (scores, XP, streaks, badges)'] },
      { strong: 'Usage Data' },
      { ul: ['Interaction with features', 'Basic analytics to improve performance'] },
    ] },
    { title: 'How We Use Information', blocks: [
      { p: 'We use your information to:' },
      { ul: ['Provide and operate the Service', 'Generate AI content (stories, learning tools, etc.)', 'Track learning progress and assignment completion', 'Improve product functionality and user experience', 'Communicate important updates'] },
      { p: 'We send three categories of email:' },
      { ul: ['Transactional — story-ready, story-failed, password reset, and other account-essential messages.', 'Educational — occasional tips and onboarding suggestions; you can unsubscribe at any time.', 'Administrative — service announcements such as billing changes or policy updates.'] },
      { p: 'You will not be enrolled in marketing email lists by default.' },
    ] },
    { title: 'AI Processing', blocks: [
      { p: 'To generate content, user inputs may be sent to third-party AI providers (such as OpenAI). These providers process data solely to return results to the Service.' },
      { p: 'We do not use your content to train external AI models.' },
    ] },
    { title: 'Cookies and Local Storage', blocks: [
      { p: 'We use a small number of essential cookies and browser storage entries:' },
      { ul: ['An authentication session cookie so you stay signed in.', 'A guest token (when applicable) so a guest submission can be claimed on later sign-up.', 'Preference flags such as language, theme or cookie-banner dismissal.'] },
      { p: 'We do not use third-party advertising trackers.' },
    ] },
    { title: 'Student and Minor Data', blocks: [
      { p: "Students participate in Nest & Quill through a classroom managed by an educator or, in the home setting, with a parent's supervision. The educator or parent is responsible for obtaining any consent required by their school, district, or local law before enrolling a student." },
      { p: "We collect only the data needed to operate the educational service the educator or parent has requested: the student's display name, optional avatar, classroom membership, and the student's responses to assigned activities. We do not sell or share student data, and we do not use student-submitted content to train external AI models." },
      { p: "A student's submissions are visible to the educator who owns the classroom and to Nest & Quill administrators for support and moderation. They are not shared with sponsors or with other students unless the educator explicitly enables that within a feature." },
    ] },
    { title: 'Adult Content Data', blocks: [
      { p: 'When users opt into adult story creation, we collect an additional consent acknowledgment confirming the user is at least 18 years old. This consent record is stored alongside the story request.' },
      { p: 'Adult story content is generated using a separate AI configuration. The same data handling and retention policies apply to adult stories as to all other content on the platform.' },
    ] },
    { title: 'Data Sharing', blocks: [
      { p: 'We do not sell your personal information.' },
      { p: 'We may share data with:' },
      { ul: ['Service providers (e.g., hosting, payments, email delivery)', 'AI providers for content generation', 'Legal authorities when required'] },
      { p: 'We may also partner with brands (“Sponsors”) who fund classroom rewards. Sponsors do not receive student personal data. If you redeem a sponsor-funded reward, only the information needed to fulfill the reward is shared with the relevant Sponsor or fulfillment partner.' },
    ] },
    { title: 'Data Security', blocks: [
      { p: 'We use reasonable safeguards to protect your data. However, no system is completely secure.' },
    ] },
    { title: 'Data Retention', blocks: [
      { p: 'We retain account data for as long as you have an account with us. Stories you archive remain in our system in a hidden state and can be restored from your account.' },
      { p: 'To request permanent deletion of your account or specific stories, contact support; we will remove the data from our active databases within 30 days, subject to backup retention windows.' },
    ] },
    { title: 'Your Rights', blocks: [
      { p: 'You may:' },
      { ul: ['Access or update your information', 'Request account deletion', 'Contact us with privacy concerns'] },
    ] },
    { title: 'Changes to This Policy', blocks: [
      { p: 'We may update this policy from time to time. Continued use of the Service indicates acceptance of updates.' },
    ] },
    { title: 'Contact', blocks: [{ contact: 'For privacy-related questions, contact:' }] },
  ],
}

const privacyEs: LegalDoc = {
  title: 'Política de privacidad',
  updated: 'Última actualización: mayo de 2026',
  operator: 'Nest & Quill es operado por Bright Tale Books.',
  sections: [
    { title: 'Resumen', blocks: [
      { p: 'Esta Política de privacidad explica qué información recopilamos, cómo la usamos y cómo la protegemos.' },
      { p: 'Al usar el Servicio, aceptas esta política.' },
    ] },
    { title: 'Aviso de beta', beta: true, blocks: [
      { p: 'Nest & Quill se encuentra actualmente en beta. Algunas funciones de pago pueden ser gratuitas durante este periodo y ciertas capacidades (como la generación de ilustraciones) pueden pausarse o limitarse. Avisaremos con un plazo razonable antes de activar la facturación o retirar las concesiones de la beta.' },
    ] },
    { title: 'Información que recopilamos', blocks: [
      { strong: 'Información de la cuenta' },
      { ul: ['Nombre', 'Dirección de correo electrónico', 'Rol de la cuenta (padre o madre, estudiante, educador)', 'Token de invitado (una cookie por navegador) cuando envías un cuento sin iniciar sesión, para poder mostrarte el cuento en curso y, si luego creas una cuenta con el mismo correo, vincular el cuento a tu cuenta.'] },
      { strong: 'Contenido del usuario' },
      { ul: ['Entradas y preferencias de los cuentos (incluidos borradores y cuentos enviados)', 'Material del Asistente de estudio (texto o imágenes que proporcionas para aprender)', 'Respuestas de cuestionarios, de tarjetas de memoria y otras entregas de actividades de aprendizaje', 'Notificaciones dentro de la app dirigidas a tu cuenta (títulos, enlaces, estado de lectura)'] },
      { strong: 'Datos del salón de clases' },
      { ul: ['Membresías de clases', 'Tareas y entregas', 'Datos de progreso (puntuaciones, XP, rachas, insignias)'] },
      { strong: 'Datos de uso' },
      { ul: ['Interacción con las funciones', 'Analítica básica para mejorar el rendimiento'] },
    ] },
    { title: 'Cómo usamos la información', blocks: [
      { p: 'Usamos tu información para:' },
      { ul: ['Proporcionar y operar el Servicio', 'Generar contenido con IA (cuentos, herramientas de aprendizaje, etc.)', 'Hacer seguimiento del progreso de aprendizaje y de la finalización de tareas', 'Mejorar la funcionalidad del producto y la experiencia de usuario', 'Comunicar actualizaciones importantes'] },
      { p: 'Enviamos tres categorías de correo electrónico:' },
      { ul: ['Transaccionales: cuento listo, cuento fallido, restablecimiento de contraseña y otros mensajes esenciales de la cuenta.', 'Educativos: consejos ocasionales y sugerencias de inicio; puedes darte de baja en cualquier momento.', 'Administrativos: anuncios del servicio, como cambios de facturación o actualizaciones de políticas.'] },
      { p: 'No se te inscribirá en listas de correo de marketing de forma predeterminada.' },
    ] },
    { title: 'Procesamiento con IA', blocks: [
      { p: 'Para generar contenido, las entradas del usuario pueden enviarse a proveedores de IA externos (como OpenAI). Estos proveedores procesan los datos únicamente para devolver resultados al Servicio.' },
      { p: 'No usamos tu contenido para entrenar modelos de IA externos.' },
    ] },
    { title: 'Cookies y almacenamiento local', blocks: [
      { p: 'Usamos un pequeño número de cookies esenciales y entradas de almacenamiento del navegador:' },
      { ul: ['Una cookie de sesión de autenticación para que sigas con la sesión iniciada.', 'Un token de invitado (cuando corresponde) para que un envío como invitado pueda reclamarse al registrarte después.', 'Indicadores de preferencias, como el idioma, el tema o el cierre del aviso de cookies.'] },
      { p: 'No usamos rastreadores publicitarios de terceros.' },
    ] },
    { title: 'Datos de estudiantes y menores', blocks: [
      { p: 'Los estudiantes participan en Nest & Quill a través de un salón de clases administrado por un educador o, en el entorno del hogar, con la supervisión de un padre o una madre. El educador o el padre es responsable de obtener cualquier consentimiento que exija su escuela, distrito o la ley local antes de inscribir a un estudiante.' },
      { p: 'Recopilamos solo los datos necesarios para operar el servicio educativo que el educador o el padre ha solicitado: el nombre visible del estudiante, un avatar opcional, la membresía del salón y las respuestas del estudiante a las actividades asignadas. No vendemos ni compartimos los datos de los estudiantes, y no usamos el contenido enviado por los estudiantes para entrenar modelos de IA externos.' },
      { p: 'Las entregas de un estudiante son visibles para el educador propietario del salón y para los administradores de Nest & Quill con fines de soporte y moderación. No se comparten con patrocinadores ni con otros estudiantes a menos que el educador lo habilite explícitamente dentro de una función.' },
    ] },
    { title: 'Datos de contenido para adultos', blocks: [
      { p: 'Cuando los usuarios optan por crear historias para adultos, recopilamos un consentimiento adicional que confirma que el usuario tiene al menos 18 años. Este registro de consentimiento se guarda junto con la solicitud del cuento.' },
      { p: 'El contenido de las historias para adultos se genera con una configuración de IA independiente. A las historias para adultos se les aplican las mismas políticas de manejo y retención de datos que al resto del contenido de la plataforma.' },
    ] },
    { title: 'Compartir datos', blocks: [
      { p: 'No vendemos tu información personal.' },
      { p: 'Podemos compartir datos con:' },
      { ul: ['Proveedores de servicios (por ejemplo, alojamiento, pagos, entrega de correo)', 'Proveedores de IA para la generación de contenido', 'Autoridades legales cuando sea requerido'] },
      { p: 'También podemos asociarnos con marcas (“Patrocinadores”) que financian recompensas para los salones de clases. Los Patrocinadores no reciben datos personales de los estudiantes. Si canjeas una recompensa financiada por un patrocinador, solo se comparte con el Patrocinador o socio de entrega correspondiente la información necesaria para entregar la recompensa.' },
    ] },
    { title: 'Seguridad de los datos', blocks: [
      { p: 'Aplicamos medidas razonables para proteger tus datos. Sin embargo, ningún sistema es completamente seguro.' },
    ] },
    { title: 'Conservación de los datos', blocks: [
      { p: 'Conservamos los datos de tu cuenta mientras tengas una cuenta con nosotros. Los cuentos que archives permanecen en nuestro sistema en estado oculto y pueden restaurarse desde tu cuenta.' },
      { p: 'Para solicitar la eliminación permanente de tu cuenta o de cuentos específicos, contacta a soporte; retiraremos los datos de nuestras bases de datos activas en un plazo de 30 días, sujeto a los periodos de retención de copias de seguridad.' },
    ] },
    { title: 'Tus derechos', blocks: [
      { p: 'Puedes:' },
      { ul: ['Acceder a tu información o actualizarla', 'Solicitar la eliminación de tu cuenta', 'Contactarnos con inquietudes sobre privacidad'] },
    ] },
    { title: 'Cambios en esta política', blocks: [
      { p: 'Podemos actualizar esta política de vez en cuando. El uso continuado del Servicio indica la aceptación de las actualizaciones.' },
    ] },
    { title: 'Contacto', blocks: [{ contact: 'Para preguntas relacionadas con la privacidad, escríbenos a:' }] },
  ],
}

export const LEGAL_CONTACT = CONTACT
export const legal: Record<Lang, { terms: LegalDoc; privacy: LegalDoc }> = {
  en: { terms: termsEn, privacy: privacyEn },
  es: { terms: termsEs, privacy: privacyEs },
}
