INSERT INTO app_settings (key, value, category, label, description) VALUES
  -- Asset URLs
  ('branding_favicon_url',
   '"https://nestandquill.b-cdn.net/Nest%20and%20Quill%20favicon.webp"',
   'branding', 'Favicon URL', 'URL for the site favicon (browser tab icon)'),
  ('branding_header_logo_url',
   '"https://nestandquill.b-cdn.net/Nest%20and%20Quill%20Full%20Color.webp"',
   'branding', 'Header Logo URL', 'Logo displayed in the public site header'),
  ('branding_footer_logo_url',
   '"https://nestandquill.b-cdn.net/nestandquill%20brand%20start-03.webp"',
   'branding', 'Footer Logo URL', 'Logo displayed in the site footer (light version for dark bg)'),

  -- Contact info
  ('contact_email',
   '"contact@nestandquill.com"',
   'branding', 'Contact Email', 'Public contact email shown on the site and in emails'),
  ('support_email',
   '"support@nestandquill.com"',
   'branding', 'Support Email', 'Email for customer support inquiries'),
  ('stories_from_email',
   '"stories@nestandquill.com"',
   'branding', 'Stories From Email', 'Sender address for story delivery and transactional emails'),
  ('admin_alert_email',
   '"admin@nestandquill.com"',
   'branding', 'Admin Alert Email', 'Email address that receives admin notification alerts'),
  ('phone_number',
   '""',
   'branding', 'Phone Number', 'Phone number displayed on the site (leave empty to hide)'),

  -- Light mode colors
  ('color_brand_primary',
   '"#C99700"',
   'branding', 'Brand Primary (Light)', 'Primary brand color used for buttons, links, and accents'),
  ('color_oxford',
   '"#0C2340"',
   'branding', 'Oxford Navy (Light)', 'Dark navy color for headings and primary text'),
  ('color_parchment',
   '"#F8F5EC"',
   'branding', 'Parchment Background (Light)', 'Light cream background color'),
  ('color_charcoal',
   '"#2E2E2E"',
   'branding', 'Charcoal Text (Light)', 'Body text color'),

  -- Dark mode colors
  ('color_dark_brand_primary',
   '"#DDB328"',
   'branding', 'Brand Primary (Dark)', 'Primary brand color in dark mode'),
  ('color_dark_bg',
   '"#030712"',
   'branding', 'Background (Dark)', 'Main background color in dark mode'),
  ('color_dark_surface',
   '"#111827"',
   'branding', 'Surface (Dark)', 'Card/surface background in dark mode'),
  ('color_dark_text',
   '"#F3F4F6"',
   'branding', 'Text (Dark)', 'Primary text color in dark mode'),
  ('color_dark_muted',
   '"#9CA3AF"',
   'branding', 'Muted Text (Dark)', 'Secondary/muted text color in dark mode')
ON CONFLICT (key) DO NOTHING;
