-- ── Learning mode fields on story_requests ────────────────────────────────────

ALTER TABLE public.story_requests
  ADD COLUMN IF NOT EXISTS learning_mode      BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS learning_subject   TEXT,
  ADD COLUMN IF NOT EXISTS learning_grade     SMALLINT,
  ADD COLUMN IF NOT EXISTS learning_topic     TEXT;

-- ── Quiz questions (generated by AI, stored per story) ────────────────────────

CREATE TABLE public.story_quizzes (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  request_id  UUID NOT NULL REFERENCES public.story_requests(id) ON DELETE CASCADE,
  subject     TEXT,
  grade       SMALLINT,
  topic       TEXT,
  questions   JSONB NOT NULL DEFAULT '[]',
  -- Each question: { question, options: string[4], correct_index: 0-3, explanation }
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX idx_story_quizzes_request ON public.story_quizzes (request_id);

-- ── Quiz results (one row per attempt) ───────────────────────────────────────

CREATE TABLE public.quiz_results (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  request_id  UUID NOT NULL REFERENCES public.story_requests(id) ON DELETE CASCADE,
  user_id     UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  guest_token TEXT,
  score       SMALLINT NOT NULL,
  total       SMALLINT NOT NULL,
  answers     JSONB NOT NULL DEFAULT '[]',
  -- Each answer: { question_index, selected_index, correct }
  completed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_quiz_results_request   ON public.quiz_results (request_id);
CREATE INDEX idx_quiz_results_user      ON public.quiz_results (user_id);

-- RLS
ALTER TABLE public.story_quizzes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quiz_results  ENABLE ROW LEVEL SECURITY;

-- Anyone can read quizzes for stories they can access (handled at API level)
CREATE POLICY "Service role full access to story_quizzes"
  ON public.story_quizzes FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY "Service role full access to quiz_results"
  ON public.quiz_results FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY "Users can read own quiz results"
  ON public.quiz_results FOR SELECT TO authenticated
  USING (user_id = auth.uid());
